(function(g){var window=this;var yva=function(a,b){var c=[];g.Dl(b,function(a){try{var b=g.mD.prototype.o.call(this,a,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}g.t(b)?g.lD(b)&&c.push(a):c.push(a)},a);
return c},zva=function(a,b){var c=yva(a,b);
(0,g.H)(c,function(a){g.mD.prototype.remove.call(this,a)},a)},i9=function(a,b){g.S0.call(this,g.T("YTP_MDX_TITLE"),0,a,b);
this.aa=a;this.F={};this.T(a,"onMdxReceiversChange",this.J);this.T(a,"presentingplayerstatechange",this.J);this.J()},Ava=function(){var a=g.IG;
zva(a,a.g.Od(!0))},j9=function(a){g.kH.call(this,"ScreenServiceProxy");
this.Xc=a;this.o=[];this.o.push(this.Xc.$_s("screenChange",(0,g.B)(this.KR,this)));this.o.push(this.Xc.$_s("onlineScreenChange",(0,g.B)(this.YN,this)))},k9=function(a){g.YG("cloudview",a)},Bva=function(a){k9("setApiReady_ "+a);
g.u("yt.mdx.remote.cloudview.apiReady_",a,void 0)},l9=function(){return g.w("yt.mdx.remote.cloudview.instance_")},Cva=function(a){g.$F[a]&&(a=g.$F[a],(0,g.H)(a,function(a){g.YF[a]&&delete g.YF[a]}),a.length=0)},m9=function(){return g.w("yt.mdx.remote.connection_")},n9=function(a){g.u("yt.mdx.remote.connectData_",a,void 0)},Dva=function(a){g.u("yt.mdx.remote.currentScreenId_",a,void 0)},o9=function(){return g.w("yt.mdx.remote.currentScreenId_")},q9=function(){if(!p9){var a=g.w("yt.mdx.remote.screenService_");
p9=a?new j9(a):null}return p9},r9=function(a){g.u("yt.mdx.remote.cloudview.initializing_",a,void 0)},s9=function(){return!!g.w("yt.mdx.remote.cloudview.apiReady_")},t9=function(a){k9("setCastInstalled_ "+a);
g.KG("yt-remote-cast-installed",a)},u9=function(a){g.YG("cloudview",a)},Eva=function(a,b){l9().init(a,b)},v9=function(){return!!g.LG("yt-remote-cast-installed")},Fva=function(){k9("dispose");
var a=l9();a&&a.dispose();g.u("yt.mdx.remote.cloudview.instance_",null,void 0);Bva(!1);g.bG(w9);w9.length=0},Gva=function(){var a=window.document.createElement("a");
g.Nd(a,"https://www.gstatic.com/cv/js/sender/v1/cast_sender.js");a=a.href.replace(/^[a-zA-Z]+:\/\//,"//");return"js-"+g.Sa(a)},Hva=function(a,b){var c=window.document.createElement("script");
c.id=a;c.onload=function(){b&&(0,window.setTimeout)(b,0)};
c.onreadystatechange=function(){switch(c.readyState){case "loaded":case "complete":c.onload()}};
c.src="https://www.gstatic.com/cv/js/sender/v1/cast_sender.js";var d=window.document.getElementsByTagName("head")[0]||window.document.body;d.insertBefore(c,d.firstChild);return c},Iva=function(a){var b=g.XF();
if(b)if(b.clear(a),a)Cva(a);else for(var c in g.$F)Cva(c)},x9=function(){return g.w("yt.mdx.remote.channelParams_")||{}},z9=function(a){var b=m9();
n9(null);a||Dva("");g.u("yt.mdx.remote.connection_",a,void 0);y9&&((0,g.H)(y9,function(b){b(a)}),y9.length=0);
b&&!a?g.eG("yt-remote-connection-change",!1):!b&&a&&g.eG("yt-remote-connection-change",!0)},Jva=function(){return g.w("yt.mdx.remote.connectData_")},A9=function(){var a=o9();
if(!a)return null;var b=q9().Ud();return g.jH(b,a)},Kva=function(a,b){t9(!0);
r9(!1);Eva(a,function(a){a?(Bva(!0),g.cG("yt-remote-cast2-api-ready")):(u9("Failed to initialize cast API."),t9(!1),g.MG("yt-remote-cast-available"),g.MG("yt-remote-cast-receiver"),Fva());b(a)})},Lva=function(){return v9()?l9()?l9().getCastSession():(u9("getCastSelector: Cast is not initialized."),null):(u9("getCastSelector: Cast API is not installed!"),null)},Mva=function(){var a=Gva(),b=window.document.getElementById(a),c=b&&g.mF(b,"loaded");
c||b&&!c||(b=Hva(a,function(){g.mF(b,"loaded")||(g.nF(b,"loaded","true"),g.cG(a),g.uE(g.ya(Iva,a),0))}))},Nva=function(a){return(0,g.I)(a,function(a){return{key:a.id,
name:a.name}})},Ova=function(){if(g.yoa){var a=2,b=g.Dh(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;g.Ih("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",g.Fh,c)}},C9=function(a,b){o9();
A9()&&A9();Dva(a.id);var c=new g.oI(B9,a,x9());c.connect(b,Jva());c.subscribe("beforeDisconnect",function(a){g.eG("yt-remote-before-disconnect",a)});
c.subscribe("beforeDispose",function(){m9()&&(m9(),z9(null))});
z9(c)},D9=function(){var a=g.pH();
if(!a)return null;var b=q9().Ud();return g.jH(b,a)},E9=function(a){g.YG("remote",a)},F9=function(){var a=m9();
return!!a&&3!=a.getProxyState()},G9=function(){s9()?l9().stopSession():u9("stopSession called before API ready.");
var a=m9();a&&(a.disconnect(1),z9(null))},Pva=function(){var a=q9().Xc.$_gos();
var b=A9();b&&m9()&&(g.iH(a,b)||a.push(b));return Nva(a)},I9=function(a,b){g.NF.call(this);
this.g=0;this.B=a;this.D=[];this.C=new g.AB;this.A=this.o=null;this.J=(0,g.B)(this.fM,this);this.F=(0,g.B)(this.Lk,this);this.G=(0,g.B)(this.eM,this);this.K=(0,g.B)(this.sM,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.Qs,this),Qva(this))):c=3;0!=c&&(b?this.Qs(c):g.uE((0,g.B)(function(){this.Qs(c)},this),0));
var d=Lva();d&&H9(this,d);this.subscribe("yt-remote-cast2-session-change",this.K)},J9=function(a){return new g.dI(a.B.getPlayerContextData())},Rva=function(a,b,c,d,e){var f=J9(a),k=e||f.listId;
d=d||0;var l={videoId:b,currentIndex:d};g.hI(f,b,d);g.t(c)&&(g.fI(f,c),l.currentTime=c);g.t(k)&&(l.listId=k);K9(a,"setPlaylist",l);e||L9(a,f)},Qva=function(a){(0,g.H)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(a){this.D.push(this.B.subscribe(a,g.ya(this.sO,a),this))},a)},Sva=function(a){(0,g.H)(a.D,function(a){this.B.unsubscribeByKey(a)},a);
a.D.length=0},M9=function(a,b){50>a.C.Kc()&&g.CB(a.C,b)},N9=function(a,b,c){var d=J9(a);
g.fI(d,c);-1E3!=d.g&&(d.g=b);L9(a,d)},K9=function(a,b,c){a.B.sendMessage(b,c)},L9=function(a,b){Sva(a);
a.B.setPlayerContextData(g.iI(b));Qva(a)},H9=function(a,b){a.A&&(a.A.removeUpdateListener(a.J),a.A.removeMediaListener(a.F),a.Lk(null));
a.A=b;a.A&&(O9("Setting cast session: "+a.A.sessionId),a.A.addUpdateListener(a.J),a.A.addMediaListener(a.F),a.A.media.length&&a.Lk(a.A.media[0]))},Tva=function(a){var b=a.o.media,c=a.o.customData;
if(b&&c){var d=J9(a);b.contentId!=d.videoId&&O9("Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.g=c.playerState;g.fI(d,a.o.getEstimatedTime());L9(a,d)}else O9("No cast media video. Ignoring state update.")},O9=function(a){g.YG("CP",a)},P9=function(a,b,c){return(0,g.B)(function(a){this.jc("Failed to "+b+" with cast v2 channel. Error code: "+a.code);
a.code!=window.chrome.cast.ErrorCode.TIMEOUT&&(this.jc("Retrying "+b+" using MDx browser channel."),K9(this,b,c))},a)},Uva=function(a,b){var c=!1;
l9()||(c=new g.YH(a,b),c.subscribe("yt-remote-cast2-availability-change",function(a){g.KG("yt-remote-cast-available",a);g.eG("yt-remote-cast2-availability-change",a)}),c.subscribe("yt-remote-cast2-receiver-selected",function(a){k9("onReceiverSelected: "+a.friendlyName);
g.KG("yt-remote-cast-receiver",a);g.eG("yt-remote-cast2-receiver-selected",a)}),c.subscribe("yt-remote-cast2-receiver-resumed",function(a){k9("onReceiverResumed: "+a.friendlyName);
g.KG("yt-remote-cast-receiver",a)}),c.subscribe("yt-remote-cast2-session-change",function(a){k9("onSessionChange: "+g.fH(a));
a||g.MG("yt-remote-cast-receiver");g.eG("yt-remote-cast2-session-change",a)}),g.u("yt.mdx.remote.cloudview.instance_",c,void 0),c=!0);
k9("cloudview.createSingleton_: "+c);return c},Vva=function(){var a=0<=g.Gb.search(/\ (CrMo|Chrome|CriOS)\//);
return g.RE||a},Q9=function(a,b){s9()?l9().setConnectedScreenStatus(a,b):u9("setConnectedScreenStatus called before ready.")},Wva=function(){k9("clearCurrentReceiver");
g.MG("yt-remote-cast-receiver")},Xva=function(){if(0<=window.navigator.userAgent.indexOf("CriOS")){var a=window.__gCrWeb&&window.__gCrWeb.message&&window.__gCrWeb.message.invokeOnHost;
if(a){Ova();a({command:"cast.sender.init"});return}}if(window.chrome)if(Ova(),a=window.navigator.userAgent,0<=a.indexOf("Android")&&0<=a.indexOf("Chrome/")&&window.navigator.presentation){var a="",b=g.Bh();55<=b?a="55":50<=b&&(a="50");g.Ih("//www.gstatic.com/eureka/clank"+a+g.Gh,g.Fh)}else g.Jh(0);else g.Fh()},Yva=function(a){a?(g.KG("yt-remote-session-app",a.app),g.KG("yt-remote-session-name",a.name)):(g.MG("yt-remote-session-app"),g.MG("yt-remote-session-name"));
g.u("yt.mdx.remote.channelParams_",a,void 0)},Zva=function(){var a=x9();
if(g.Tb(a)){var a=g.oH(),b=g.LG("yt-remote-session-name")||"",c=g.LG("yt-remote-session-app")||"",a={device:"REMOTE_CONTROL",id:a,name:b,app:c,"mdx-version":3};g.u("yt.mdx.remote.channelParams_",a,void 0)}},$va=function(){var a=D9();
a?(E9("Resume connection to: "+g.fH(a)),C9(a,0)):(g.xH(),Wva(),E9("Skipping connecting because no session screen found."))},awa=function(a){E9("remote.onCastSessionChange_: "+g.fH(a));
if(a){var b=A9();b&&b.id==a.id?Q9(b.id,"YouTube TV"):(b&&G9(),C9(a,1))}else m9()&&G9()},bwa=function(){var a=Pva(),b=A9();
b||(b=D9());return g.$a(a,function(a){return b&&g.cH(b,a.key)?!0:!1})},cwa=function(){var a=g.LG("yt-remote-cast-receiver");
return a?a.friendlyName:null},dwa=function(a,b,c,d,e){Vva()?Uva(b,e)&&(r9(!0),window.chrome&&window.chrome.cast&&window.chrome.cast.isAvailable?Kva(a,c):(window.__onGCastApiAvailable=function(b,d){b?Kva(a,c):(u9("Failed to load cast API: "+d),t9(!1),r9(!1),g.MG("yt-remote-cast-available"),g.MG("yt-remote-cast-receiver"),Fva(),c(!1))},d?window.spf?window.spf.script.load("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js","",void 0):Mva():Xva())):k9("Cannot initialize because not running Chrome")},
ewa=function(a){this.port=this.domain="";
this.g="/api/lounge";this.o=!0;a=a||window.document.location.href;var b=g.vg(a)||"";b&&(this.port=":"+b);this.domain=g.ug(a)||"";a=g.Gb;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Ra(a,"10.0")&&(this.o=!1))},fwa=function(a){for(var b,c=[];!(b=a.next()).done;)c.push(b.value);
return c},R9=function(){var a=bwa();
!a&&v9()&&cwa()&&(a={key:"cast-selector-receiver",name:cwa()});return a},gwa=function(){var a=Pva();
v9()&&g.LG("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},hwa=function(a){var b={device:"Desktop",
app:"youtube-desktop"};g.IG&&Ava();g.rH();B9||(B9=new ewa,g.zH()&&(B9.g="/api/loungedev"));y9||(y9=g.w("yt.mdx.remote.deferredProxies_")||[],g.u("yt.mdx.remote.deferredProxies_",y9,void 0));Zva();var c=q9();if(!c){var d=new g.KH(B9);g.u("yt.mdx.remote.screenService_",d,void 0);c=q9();dwa(a,d,function(a){a?o9()&&Q9(o9(),"YouTube TV"):d.subscribe("onlineScreenChange",function(){g.eG("yt-remote-receiver-availability-change")})},!(!b||!b.loadCastApiSetupScript),b?b.appId:void 0)}b&&!g.w("yt.mdx.remote.initialized_")&&
(g.u("yt.mdx.remote.initialized_",!0,void 0),E9("Initializing: "+g.Lc(b)),S9.push(g.aG("yt-remote-cast2-availability-change",function(){g.eG("yt-remote-receiver-availability-change")})),S9.push(g.aG("yt-remote-cast2-receiver-selected",function(){n9(null);
g.eG("yt-remote-auto-connect","cast-selector-receiver")})),S9.push(g.aG("yt-remote-cast2-receiver-resumed",function(){g.eG("yt-remote-receiver-resumed","cast-selector-receiver")})),S9.push(g.aG("yt-remote-cast2-session-change",awa)),S9.push(g.aG("yt-remote-connection-change",function(a){a?Q9(o9(),"YouTube TV"):D9()||(Q9(null,null),Wva())})),a=x9(),b.isAuto&&(a.id+="#dial"),g.TF("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,E9(" -- with channel params: "+g.Lc(a)),
Yva(a),c.start(),o9()||$va())},T9=function(){v9()?l9()?s9()?(k9("Requesting cast selector."),l9().requestSession()):(k9("Wait for cast API to be ready to request the session."),w9.push(g.aG("yt-remote-cast2-api-ready",T9))):u9("requestCastSelector: Cast is not initialized."):u9("requestCastSelector: Cast API is not installed!")},U9=function(a,b,c){g.M.call(this);
this.F=a;this.aa=b;this.o=new g.EL(this);g.N(this,this.o);this.o.T(b,"onCaptionsTrackListChanged",this.rN);this.o.T(b,"captionschanged",this.dM);this.o.T(b,"captionssettingschanged",this.QA);this.o.T(b,"videoplayerreset",this.wn);this.o.T(b,"mdxautoplaycancel",this.qF);this.O=this.o.T(b,"onVolumeChange",this.nz);this.D=!1;this.g=c;c.subscribe("proxyStateChange",this.Az,this);c.subscribe("remotePlayerChange",this.Nk,this);c.subscribe("remoteQueueChange",this.wn,this);c.subscribe("autoplayUpNext",this.Zy,
this);c.subscribe("previousNextChange",this.xz,this);c.subscribe("nowAutoplaying",this.oz,this);c.subscribe("autoplayDismissed",this.Yy,this);this.suggestion=null;this.G=new g.OQ(64);this.A=new g.pt(this.LA,500,this);g.N(this,this.A);this.B=new g.pt(this.MA,1E3,this);g.N(this,this.B);this.C={};this.K=new g.pt(this.aB,1E3,this);g.N(this,this.K);this.J=new g.ck(this.vS,1E3,this);g.N(this,this.J);this.M=g.y;this.QA();this.wn();this.Nk()},V9=function(a,b){var c=a.F,d=a.aa.ia().lengthSeconds;
c.J=b||0;c.g.Y("progresssync",b,d)},iwa=function(a){V9(a,0);
a.A.stop();W9(a,new g.OQ(64))},Z9=function(a,b){if(X9(a)&&!a.D){var c=null;
b&&(c={style:a.aa.Dk()},g.$b(c,b));a.g.FA(Y9(a),c);a.C=J9(a.g).o}},$9=function(a,b){var c=a.aa.Kf();
c?Rva(a.g,Y9(a),b,c.Sd(),c.listId.toString()):Rva(a.g,Y9(a),b);W9(a,new g.OQ(1))},jwa=function(a,b){if(b){var c=a.aa.Yc("captions","tracklist",{Rw:1});
c&&c.length?(a.aa.Fe("captions","track",b),a.D=!1):(a.aa.zk("captions"),a.D=!0)}else a.aa.Fe("captions","track",{})},X9=function(a){return J9(a.g).videoId==Y9(a)},Y9=function(a){return a.aa.ia().videoId},W9=function(a,b){a.B.stop();
var c=a.G;if(!g.UQ(c,b)){var d=g.V(b,2);if(d!=g.V(a.G,2)){var e=a.aa,f=e.playerType;(e=g.ZU(e.app,void 0===f?1:f))&&g.VT(e,d)}a.G=b;kwa(a.F,c,b)}},a$=function(a){g.W.call(this,{H:"div",
N:"ytp-remote",L:[{H:"div",N:"ytp-remote-display-status",L:[{H:"div",N:"ytp-remote-display-status-icon",L:[g.RD()]},{H:"div",N:"ytp-remote-display-status-text",L:["{{statustext}}"]}]}]});this.o=new g.MV(this,250);g.N(this,this.o);this.A=a;this.T(a,"presentingplayerstatechange",this.B);lwa(this,g.$U(a))},lwa=function(a,b){if(3==a.A.Ya()){var c={RECEIVER_NAME:a.A.Yc("remote","currentReceiver").name},c=g.V(b,128)?g.T("YTP_MDX_STATUS_ERROR_2",c):b.wb()||g.V(b,4)?g.T("YTP_MDX_STATUS_PLAYING_2",c):g.T("YTP_MDX_STATUS_CONNECTED_2",
c);
a.Ca("statustext",c);a.o.show()}else a.o.hide()},b$=function(a){g.BV.call(this,a);
this.A={key:g.hH(),name:g.T("YTP_MDX_MY_COMPUTER")};this.C=null;this.D=[];this.K=this.o=null;this.G=[this.A];this.B=this.A;this.F=new g.OQ(64);this.J=0;var b=g.TU(a).C;b&&(b=b.A&&b.A.g)&&(b=new i9(a,b),g.N(this,b));b=new a$(a);g.N(this,b);g.qV(a,b.element,5)},kwa=function(a,b,c){a.F=c;
a.g.Y("presentingplayerstatechange",new g.LT(c,b))},c$=function(a,b){if(b.key!=a.B.key)if(b.key==a.A.key)G9();
else{a.B=b;var c=a.g.getPlaylistId();var d=a.g.ia().videoId;if(c||d){var e=a.g.Kf();if(e){var f=[];for(var k=0;k<e.getLength();k++)f[k]=e.gc(k).videoId}else f=[a.g.ia().videoId];c={videoIds:f,listId:c,videoId:d,index:Math.max(a.g.Gx(),0),currentTime:a.g.getCurrentTime()}}else c=null;E9("Connecting to: "+g.Lc(b));"cast-selector-receiver"==b.key?(n9(c||null),c=c||null,s9()?l9().setLaunchParams(c):u9("setLaunchParams called before ready.")):!c&&F9()&&o9()==b.key?g.eG("yt-remote-connection-change",!0):
(G9(),n9(c||null),c=q9().Ud(),(c=g.jH(c,b.key))&&C9(c,1))}};
g.p(i9,g.S0);i9.prototype.J=function(){var a=this.aa.Yc("remote","receivers");a&&1<a.length&&!this.aa.Yc("remote","quickCast")?(this.F=g.Cb(a,this.B,this),g.U0(this,(0,g.I)(a,this.B)),a=this.aa.Yc("remote","currentReceiver"),g.T0(this,this.B(a)),this.enable(!0)):this.enable(!1)};
i9.prototype.B=function(a){return a.key};
i9.prototype.Oe=function(a){return"cast-selector-receiver"==a?g.T("YTP_MDX_CAST_SELECTOR"):this.F[a].name};
i9.prototype.jd=function(a){g.S0.prototype.jd.call(this,a);this.aa.Fe("remote","currentReceiver",this.F[a]);this.A.bc()};
g.C(j9,g.kH);g.h=j9.prototype;g.h.Ud=function(a){return this.Xc.$_gs(a)};
g.h.contains=function(a){return!!this.Xc.$_c(a)};
g.h.get=function(a){return this.Xc.$_g(a)};
g.h.start=function(){this.Xc.$_st()};
g.h.po=function(a,b,c){this.Xc.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.Xc.$_r(a,b,c)};
g.h.Yn=function(a,b,c,d){this.Xc.$_un(a,b,c,d)};
g.h.U=function(){for(var a=0,b=this.o.length;a<b;++a)this.Xc.$_ubk(this.o[a]);this.o.length=0;this.Xc=null;j9.X.U.call(this)};
g.h.KR=function(){this.Y("screenChange")};
g.h.YN=function(){this.Y("onlineScreenChange")};
var p9=null,w9=[],y9=null,B9=null;g.C(I9,g.NF);g.h=I9.prototype;g.h.play=function(){1==this.g?(this.o?this.o.play(null,g.y,P9(this,"play")):K9(this,"play"),N9(this,1,g.gI(J9(this))),this.Y("remotePlayerChange")):M9(this,this.play)};
g.h.pause=function(){1==this.g?(this.o?this.o.pause(null,g.y,P9(this,"pause")):K9(this,"pause"),N9(this,2,g.gI(J9(this))),this.Y("remotePlayerChange")):M9(this,this.pause)};
g.h.kB=function(a){if(1==this.g){if(this.o){var b=J9(this),c=new window.chrome.cast.media.SeekRequest;c.currentTime=a;c.resumeState=b.wb()||3==b.g?window.chrome.cast.media.ResumeState.PLAYBACK_START:window.chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.o.seek(c,g.y,P9(this,"seekTo",{newTime:a}))}else K9(this,"seekTo",{newTime:a});N9(this,3,a);this.Y("remotePlayerChange")}else M9(this,g.ya(this.kB,a))};
g.h.stop=function(){if(1==this.g){this.o?this.o.stop(null,g.y,P9(this,"stopVideo")):K9(this,"stopVideo");var a=J9(this);a.index=-1;a.videoId="";g.eI(a);L9(this,a);this.Y("remotePlayerChange")}else M9(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.g){var c=J9(this);if(this.A){if(c.volume!=a){var d=Math.round(a)/100;this.A.setReceiverVolumeLevel(d,(0,g.B)(function(){O9("set receiver volume: "+d)},this),(0,g.B)(function(){this.jc("failed to set receiver volume.")},this))}c.muted!=b&&this.A.setReceiverMuted(b,(0,g.B)(function(){O9("set receiver muted: "+b)},this),(0,g.B)(function(){this.jc("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);K9(this,"setVolume",e)}c.muted=b;c.volume=a;L9(this,c)}else M9(this,g.ya(this.setVolume,a,b))};
g.h.FA=function(a,b){if(1==this.g){var c=J9(this),d={videoId:a};b&&(c.o={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,format:b.format,kind:b.kind},d.style=g.Lc(b.style),g.$b(d,c.o));K9(this,"setSubtitlesTrack",d);L9(this,c)}else M9(this,g.ya(this.FA,a,b))};
g.h.Ps=function(a,b){if(1==this.g){K9(this,"setAudioTrack",{videoId:a,audioTrackId:b.Pc.id});var c=J9(this);c.audioTrackId=b.Pc.id;L9(this,c)}else M9(this,g.ya(this.Ps,a,b))};
g.h.jB=function(a,b){if(1==this.g){if(a&&b){var c=J9(this);g.hI(c,a,b);L9(this,c)}K9(this,"previous")}else M9(this,g.ya(this.jB,a,b))};
g.h.iB=function(a,b){if(1==this.g){if(a&&b){var c=J9(this);g.hI(c,a,b);L9(this,c)}K9(this,"next")}else M9(this,g.ya(this.iB,a,b))};
g.h.tv=function(){1==this.g?K9(this,"dismissAutoplay"):M9(this,this.tv)};
g.h.dispose=function(){if(3!=this.g){var a=this.g;this.g=3;this.Y("proxyStateChange",a,this.g)}I9.X.dispose.call(this)};
g.h.U=function(){Sva(this);this.B=null;this.C.clear();H9(this,null);I9.X.U.call(this)};
g.h.Qs=function(a){if((a!=this.g||2==a)&&3!=this.g&&0!=a){var b=this.g;this.g=a;this.Y("proxyStateChange",b,a);if(1==a)for(;!this.C.isEmpty();)g.DB(this.C).apply(this);else 3==a&&this.dispose()}};
g.h.sO=function(a,b){this.Y(a,b)};
g.h.fM=function(a){if(!a)this.Lk(null),H9(this,null);else if(this.A.receiver.volume){a=this.A.receiver.volume;var b=J9(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)O9("Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,L9(this,b)}};
g.h.Lk=function(a){O9("Cast media: "+!!a);this.o&&this.o.removeUpdateListener(this.G);if(this.o=a)this.o.addUpdateListener(this.G),Tva(this),this.Y("remotePlayerChange")};
g.h.eM=function(a){a?(Tva(this),this.Y("remotePlayerChange")):this.Lk(null)};
g.h.sM=function(){var a=Lva();a&&H9(this,a)};
g.h.jc=function(a){g.YG("CP",a)};
var S9=[];g.h=ewa.prototype;g.h.Kh=function(a,b,c){var d=this.g;if(g.t(c)?c:this.o)d="https://"+this.domain+this.port+this.g;return g.Dg(d+a,b||{})};
g.h.Os=function(a,b,c,d){c={format:"JSON",method:"POST",context:this,timeout:5E3,withCredentials:!1,Mb:g.ya(this.FR,c,!0),onError:g.ya(this.ER,d),ad:g.ya(this.GR,d)};b&&(c.Sb=b,c.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.HE(a,c)};
g.h.FR=function(a,b,c,d){b?a(d):a({text:c.responseText})};
g.h.ER=function(a,b){a(Error("Request error: "+b.status))};
g.h.GR=function(a){a(Error("request timed out"))};
g.C(U9,g.M);g.h=U9.prototype;g.h.U=function(){U9.X.U.call(this);this.A.stop();this.B.stop();this.M();this.g.unsubscribe("proxyStateChange",this.Az,this);this.g.unsubscribe("remotePlayerChange",this.Nk,this);this.g.unsubscribe("remoteQueueChange",this.wn,this);this.g.unsubscribe("autoplayUpNext",this.Zy,this);this.g.unsubscribe("previousNextChange",this.xz,this);this.g.unsubscribe("nowAutoplaying",this.oz,this);this.g.unsubscribe("autoplayDismissed",this.Yy,this);this.g=this.F=null};
g.h.DB=function(a,b){2==this.g.g||(X9(this)?this.BG.apply(this,arguments):this.xG.apply(this,arguments))};
g.h.dM=function(a){this.DB("control_subtitles_set_track",g.Tb(a)?null:a)};
g.h.QA=function(){var a=this.aa.Yc("captions","track");g.Tb(a)||Z9(this,a)};
g.h.xG=function(a,b){var c=Array.prototype.slice.call(arguments,1);switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":$9(this,this.aa.getCurrentTime());break;case "control_seek":$9(this,c[0]);break;case "control_subtitles_set_track":Z9(this,c[0]);break;case "control_set_audio_track":c=c[0],X9(this)&&this.g.Ps(Y9(this),c)}};
g.h.BG=function(a,b){if(1081!=J9(this.g).g||"control_seek"!=a){var c=Array.prototype.slice.call(arguments,1);switch(a){case "control_toggle_play_pause":J9(this.g).wb()?this.g.pause():this.g.play();break;case "control_play":this.g.play();break;case "control_pause":this.g.pause();break;case "control_seek":this.J.Qi(c[0],c[1]);break;case "control_subtitles_set_track":Z9(this,c[0]);break;case "control_set_audio_track":c=c[0],X9(this)&&this.g.Ps(Y9(this),c)}}};
g.h.nz=function(a){if(X9(this)){this.g.unsubscribe("remotePlayerChange",this.Nk,this);var b=Math.round(a.volume);a=!!a.muted;var c=J9(this.g);if(b!=c.volume||a!=c.muted)this.g.setVolume(b,a),this.K.start();this.g.subscribe("remotePlayerChange",this.Nk,this)}};
g.h.rN=function(){g.Tb(this.C)||jwa(this,this.C);this.D=!1};
g.h.Az=function(a,b){this.B.stop();2==b&&this.MA()};
g.h.Nk=function(){if(X9(this)){this.A.stop();var a=J9(this.g);switch(a.g){case 1081:W9(this,new g.OQ(8));break;case 1:this.LA();W9(this,new g.OQ(8));break;case 1083:case 3:W9(this,new g.OQ(9));break;case 0:W9(this,new g.OQ(2));this.J.stop();V9(this,this.aa.ia().lengthSeconds);break;case 1082:W9(this,new g.OQ(4));break;case 2:W9(this,new g.OQ(4));V9(this,g.gI(a));break;case -1:W9(this,new g.OQ(64));break;case -1E3:a={errorCode:"mdx.remoteerror",message:g.T("YTP_MDX_PLAYER_ERROR")},W9(this,new g.OQ(128,
a))}var a=J9(this.g).o,b=this.C;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.format==b.format&&a.kind==b.kind:1)||(this.C=a,jwa(this,a));a=J9(this.g);-1==a.volume||Math.round(this.aa.getVolume())==a.volume&&this.aa.De()==a.muted||this.K.isActive()||this.aB()}else iwa(this)};
g.h.xz=function(){this.aa.Y("mdxpreviousnextchange")};
g.h.wn=function(){X9(this)||iwa(this)};
g.h.qF=function(){this.g.tv()};
g.h.Zy=function(a){a&&(a=g.HE("/watch_queue_ajax",{method:"GET",Tc:{action_get_watch_queue_item:1,video_id:a},Mb:(0,g.B)(this.tP,this)}))&&(this.M=(0,g.B)(a.abort,a))};
g.h.tP=function(a,b){var c=new g.fQ({videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.aa.Y("mdxautoplayupnext",c)};
g.h.oz=function(a){(0,window.isNaN)(a)||this.aa.Y("mdxnowautoplaying",a)};
g.h.Yy=function(){this.aa.Y("mdxautoplaycanceled")};
g.h.vS=function(a,b){-1==J9(this.g).g?$9(this,a):b&&this.g.kB(a)};
g.h.aB=function(){if(X9(this)){var a=J9(this.g);this.o.Aa(this.O);a.muted?this.aa.mute():this.aa.og();this.aa.setVolume(a.volume);this.O=this.o.T(this.aa,"onVolumeChange",this.nz)}};
g.h.LA=function(){this.A.stop();if(!this.g.na()){var a=J9(this.g);a.wb()&&W9(this,new g.OQ(8));V9(this,g.gI(a));this.A.start()}};
g.h.MA=function(){this.B.stop();this.A.stop();var a=this.g.B.getReconnectTimeout();2==this.g.g&&!(0,window.isNaN)(a)&&this.B.start()};g.p(a$,g.W);a$.prototype.B=function(a){lwa(this,a.state)};g.p(b$,g.BV);g.h=b$.prototype;g.h.create=function(){hwa("embedded"==g.X(this.g).g);this.D.push(g.aG("yt-remote-before-disconnect",this.aM,this));this.D.push(g.aG("yt-remote-connection-change",this.CO,this));this.D.push(g.aG("yt-remote-receiver-availability-change",this.yz,this));this.D.push(g.aG("yt-remote-auto-connect",this.AO,this));this.D.push(g.aG("yt-remote-receiver-resumed",this.zO,this));this.yz()};
g.h.load=function(){this.g.jp();g.BV.prototype.load.call(this);this.C=new U9(this,this.g,this.o);var a=Jva(),a=a?a.currentTime:0,b=F9()?new I9(m9(),void 0):null;0==a&&b&&(a=g.gI(J9(b)));0!=a&&(this.J=a||0,this.g.Y("progresssync",a,void 0));kwa(this,this.F,this.F);g.i2(this.g.app,6)};
g.h.unload=function(){this.g.Y("mdxautoplaycanceled");this.B=this.A;g.Se(this.C,this.o);this.o=this.C=null;g.BV.prototype.unload.call(this);g.i2(this.g.app,5)};
g.h.U=function(){g.bG(this.D);g.BV.prototype.U.call(this)};
g.h.Gk=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.C.DB.apply(this.C,[].concat([a],c instanceof Array?c:fwa(g.ia(c))))};
g.h.cG=function(){return this.loaded?this.C.suggestion:null};
g.h.Cf=function(){return this.o?J9(this.o).Cf:!1};
g.h.hasNext=function(){return this.o?J9(this.o).hasNext:!1};
g.h.getCurrentTime=function(){return this.J};
g.h.ZJ=function(){var a=J9(this.o),b=this.g.ia();return{allowSeeking:this.g.Ed(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.F?a.C+((0,g.G)()-a.A)/1E3:a.C,isPeggedToLive:1>=(a.F?a.B+((0,g.G)()-a.A)/1E3:a.B)-this.getCurrentTime(),loaded:a.K,seekableEnd:a.F?a.B+((0,g.G)()-a.A)/1E3:a.B,seekableStart:0<a.D?a.D+((0,g.G)()-a.A)/1E3:a.D}};
g.h.aK=function(){this.o&&this.o.iB()};
g.h.bK=function(){this.o&&this.o.jB()};
g.h.aM=function(a){1==a&&(this.K=this.o?J9(this.o):null)};
g.h.CO=function(){var a=F9()?new I9(m9(),void 0):null;if(a){var b=this.B;this.loaded&&this.unload();this.o=a;this.K=null;b.key!=this.A.key&&(this.B=b,this.load())}else g.Re(this.o),this.o=null,this.loaded&&(this.unload(),(a=this.K)&&a.videoId==this.g.ia().videoId&&this.g.Dx(a.videoId,g.gI(a)));this.g.Y("videodatachange","newdata",this.g.ia(),3)};
g.h.yz=function(){this.G=[this.A].concat(gwa());var a=R9()||this.A;c$(this,a);this.g.ya("onMdxReceiversChange")};
g.h.AO=function(){var a=R9();c$(this,a)};
g.h.zO=function(){this.B=R9()};
g.h.YJ=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.G;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?T9():c$(this,b)),this.loaded?this.B:this.A;case "quickCast":return 2==this.G.length&&"cast-selector-receiver"==this.G[1].key?(b&&T9(),!0):!1}};
g.h.cK=function(){K9(this.o,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.Jd=function(){return!1};window._exportCheck==g.Ba&&g.u("ytmod.player.remote",b$,void 0);})(_yt_player);
